"""add problematic_sips and dashboard_state tables

Revision ID: 5cf4b971d4b5
Revises: d65db8c547e7
Create Date: 2026-05-18 17:48:26.033437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf4b971d4b5'
down_revision: Union[str, None] = 'd65db8c547e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('pinned_message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problematic_sips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sip_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problematic_sips_sip_number'), 'problematic_sips', ['sip_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problematic_sips_sip_number'), table_name='problematic_sips')
    op.drop_table('problematic_sips')
    op.drop_table('dashboard_state')
    # ### end Alembic commands ###
